---
- name: play1
  become: yes
  hosts: dev
  tasks:
         - name: execute command Date
           command: date
         - name: copy file
           copy:
             src: /home/ubuntu/dev.txt
             dest: /home/ubuntu/

- name: play2
  become: yes
  hosts: prod
  tasks:
         - name: shell task
           shell: echo "install mysql"
         - name: install mysql server
           apt: name=mysql-server state=present
